### ISSUE TITLE
Unknown event 'undefined' occured. Data attached.

### ISSUE THREAD

**Issue by IlPicasso** [malko/rocketchat-gitlab-hook#18]
Unknown event 'undefined' occured. Data attached.
{
"url": {
"hash": null,
"search": null,
"query": {},
"pathname": "/hooks/yY4scaTDhWqmkuGAC/CENSORED",
"path": "/hooks/yY4scaTDhWqmkuGAC/CENSORED"
},
"url_raw": "/hooks/CENSORED",
"url_params": {
"integrationId": "yY4scaTDhWqmkuGAC",
"token": "CENSORED"
},
"content": {},
"content_raw": "[object Object]",
"headers": {
"connection": "upgrade",
"host": "chat.comugamers.com",
"x-real-ip": "162.158.62.51",
"x-forward-for": "167.114.103.105, 162.158.62.51",
"x-forward-proto": "http",
"x-nginx-proxy": "true",
"accept-encoding": "gzip",
"cf-ipcountry": "CA",
"x-forwarded-for": "167.114.103.105",
"cf-ray": "3e873985522d1876-EWR",
"x-forwarded-proto": "http",
"cf-visitor": "{\"scheme\":\"http\"}",
"user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36",
"0cf-connecting-ip": "X"
},
"user": {
"_id": "X",
"name": "X",
"username": "X"
}
}

**Comment by malko** [comment]
Hi, Which event trigger this and what is your gitlab and rocketchat version please

**Comment by alko89** [comment]
I have the same issue. I have a new instance of GitLab and Rocket.chat.
I tried using pushEvent and wikiEvent, both failed.

**Comment by jrisch** [comment]
I think this problem occurs, because these system events does not provide a `x-gitlab-event` header, which is what you use to classify the events. I've got one more example here:

```
{
"event_name": "repository_update",
"user_id": 2,
"user_name": "Awsome Gitlab User",
"user_email": "john@doe.com",
"user_avatar": "https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png",
"project_id": 270,
"project": {
"id": 270,
"name": "doe.com",
"description": "This is a description",
"web_url": "https://gitlab.doe.com/devops/doe.com",
"avatar_url": null,
"git_ssh_url": "git@gitlab.doe.com:devops/doe.com.git",
"git_http_url": "https://gitlab.doe.com/devops/doe.com.git",
"namespace": "Fab Ops",
"visibility_level": 0,
"path_with_namespace": "devops/doe.com",
"default_branch": "master",
"ci_config_path": null,
"homepage": "https://gitlab.doe.com/devops/doe.com",
"url": "git@gitlab.doe.com:devops/doe.com.git",
"ssh_url": "git@gitlab.doe.com:devops/doe.com.git",
"http_url": "https://gitlab.doe.com/devops/doe.com.git"
},
"changes": [
{
"before": "ce956f119d499fa5a16dd80d760125ec538642a8",
"after": "0b99a43fbec90c1264e55ebf8ce0596dcdc73be3",
"ref": "refs/heads/master"
}
],
"refs": [
"refs/heads/master"
]
}
```

Here there's an event_name parameter, which is not included in the event that @IlPicasso posted. These events are not listed on the Gitlab Integrations page under the project, so I think it's part of the pipeline I use.

Would it be possible to ignore unknown events..?

I'm using latest Gitlab version (10.7.3) and version 0.63.3 of Rocket.chat.

**Comment by M034B5** [comment]
@malko you need to case up the "event_name" 

user_create
user_rename
key_create
key_destroy
user_add_to_team
user_remove_from_team
user_destroy
project_create
project_rename
project_destroy
repository_update <---- merges and pushes

**Comment by malko** [comment]
I have just added two new flags ```IGNORE_UNKNOWN_EVENTS``` and ```IGNORE_ERROR_MESSAGES``` that are both false by default to keep unchanged previous behaviours. The first one will simply de-activate unknown events as proposed by @jrisch. The second one is just bonus and will avoid to post messages in case of parsing error.
Also taking a second look at @IlPicasso problem i can see there's a proxy involved and sometimes proxy can remove unknown custom headers depending on their settings. So @IlPicasso Can you check that your proxy correctly pass the x-gitlab-event headers. 
For now I close the issue but you can open it again if you don't think the fix is enough.
Also @jrisch if you want to add custom events we can probably add a fallback to search for event names in the request.content.event_name when no headers is found. But I don't deal with such events, so if you want to add them you're welcome to mare a PR.
Thank you both for reporting.
