### ISSUE TITLE
webhook not hapenning automatically

### ISSUE THREAD

**Issue by madhusudan** [malko/rocketchat-gitlab-hook#6]
Hi,
I am using this webhook with below versions, but when i do some changes in my repository through gitlab site, nothing comes to the channel, but when i click "test hook" in gitlab  it appears in chat!!

any guess what could be the issue..? also i didn't get how to use ".eslintrc.json" file is this file mandatory..?

Rocket chat version 048.2
Gitlab version : 8.7.0-rc4

**Comment by malko** [comment]
Hi, concerning the .eslintrc.json file it's only used for code style at development time, it is of no use for you as a end user. About the hook not triggered, the first thing comming to my mind is to check you have correctly check the event you want the webhook to be triggered on in the gitlab webhook configuration. If you have correctly set up all the events you want to hook to your rocket chat then perhaps ask to your rocket chat admin to check the log and in case you have some give them to me so i can understand what the problem is. Hope this help.

**Comment by graywolf336** [comment]
Also, make sure the script is enabled inside Rocket.Chat.

**Comment by madhusudan** [comment]
@malko ,
I have enabled all in gitlab webhook configuration (Push Events Tag Push Events Issues Events Note Events Merge Requests Events Build Events SSL Verification: enabled).
when i change and commit any file in gitlab web the hook should trigger, but its not happening, and no logs appear  in Rpcketchat, if i click on "Test Hook" then the message appears in "#general" channel and i can see in Rocketchat logs also.

@graywolf336 , yes of-course its enabled, else i wouldn't be getting messages in channel.

**Comment by malko** [comment]
This is probably a misconfiguration. If the test button in gitlab is working it means gitlab can correctly reach your rocketchat server. The integration script is use in many places and so i don't think it is the cause of the problem either. So it only left us with configuration problems.
On the gitlab side you seems to be ok just check that you give the right webhook url but it seems to be ok from what you're saying. So finally the problem must be in the rocket chat config can you send me a screen capture of you rocket chat settings for that hook ?

**Comment by madhusudan** [comment]
@malko , I also think some issue with gitlab configuration. is my below URL is in correct format? (some letters masked).
`https://rocketchat.exmple.com/hooks/jX4gD.......Cd/ZwGP5xHPBHuRYriY......wRFCPC7F7GppWh`

**Comment by malko** [comment]
@madhusudan yes it seems correct
